name: Build and Test

on:
  push:
    branches: [ master ] # Run on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Run on Ubuntu virtual machine

    steps:
      - uses: actions/checkout@v3 # Checkout code from the repository
      - name: Install dependencies # Install any required dependencies (eg npm install)
        run: npm install
      - name: Run tests # Run your automated tests (eg npm test)
        run: npm test